"""Add new field to EEGRecord

Revision ID: c9ec9dc29328
Revises: 5096f2527dec
Create Date: 2025-10-06 06:08:30.880951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ec9dc29328'
down_revision: Union[str, Sequence[str], None] = '5096f2527dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_eeg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('focus', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.Column('wellness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_user_date', 'daily_eeg_records', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_eeg_records_id'), 'daily_eeg_records', ['id'], unique=False)
    op.create_index(op.f('ix_daily_eeg_records_user_id'), 'daily_eeg_records', ['user_id'], unique=False)
    op.create_table('eeg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('focus_label', sa.Float(), nullable=True),
    sa.Column('stress_label', sa.Float(), nullable=True),
    sa.Column('wellness_label', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eeg_records_id'), 'eeg_records', ['id'], unique=False)
    op.create_index(op.f('ix_eeg_records_user_id'), 'eeg_records', ['user_id'], unique=False)
    op.create_table('eeg_records_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('focus_label', sa.Float(), nullable=True),
    sa.Column('stress_label', sa.Float(), nullable=True),
    sa.Column('wellness_label', sa.Float(), nullable=True),
    sa.Column('backup_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backup_timestamp', 'eeg_records_backup', ['timestamp'], unique=False)
    op.create_index('idx_backup_user_date', 'eeg_records_backup', ['user_id', 'backup_date'], unique=False)
    op.create_index(op.f('ix_eeg_records_backup_id'), 'eeg_records_backup', ['id'], unique=False)
    op.create_index(op.f('ix_eeg_records_backup_user_id'), 'eeg_records_backup', ['user_id'], unique=False)
    op.create_table('monthly_eeg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.Column('wellness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monthly_user_year_month', 'monthly_eeg_records', ['user_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_eeg_records_id'), 'monthly_eeg_records', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_eeg_records_user_id'), 'monthly_eeg_records', ['user_id'], unique=False)
    op.create_table('yearly_eeg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.Column('wellness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_yearly_user_year', 'yearly_eeg_records', ['user_id', 'year'], unique=False)
    op.create_index(op.f('ix_yearly_eeg_records_id'), 'yearly_eeg_records', ['id'], unique=False)
    op.create_index(op.f('ix_yearly_eeg_records_user_id'), 'yearly_eeg_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yearly_eeg_records_user_id'), table_name='yearly_eeg_records')
    op.drop_index(op.f('ix_yearly_eeg_records_id'), table_name='yearly_eeg_records')
    op.drop_index('idx_yearly_user_year', table_name='yearly_eeg_records')
    op.drop_table('yearly_eeg_records')
    op.drop_index(op.f('ix_monthly_eeg_records_user_id'), table_name='monthly_eeg_records')
    op.drop_index(op.f('ix_monthly_eeg_records_id'), table_name='monthly_eeg_records')
    op.drop_index('idx_monthly_user_year_month', table_name='monthly_eeg_records')
    op.drop_table('monthly_eeg_records')
    op.drop_index(op.f('ix_eeg_records_backup_user_id'), table_name='eeg_records_backup')
    op.drop_index(op.f('ix_eeg_records_backup_id'), table_name='eeg_records_backup')
    op.drop_index('idx_backup_user_date', table_name='eeg_records_backup')
    op.drop_index('idx_backup_timestamp', table_name='eeg_records_backup')
    op.drop_table('eeg_records_backup')
    op.drop_index(op.f('ix_eeg_records_user_id'), table_name='eeg_records')
    op.drop_index(op.f('ix_eeg_records_id'), table_name='eeg_records')
    op.drop_table('eeg_records')
    op.drop_index(op.f('ix_daily_eeg_records_user_id'), table_name='daily_eeg_records')
    op.drop_index(op.f('ix_daily_eeg_records_id'), table_name='daily_eeg_records')
    op.drop_index('idx_daily_user_date', table_name='daily_eeg_records')
    op.drop_table('daily_eeg_records')
    # ### end Alembic commands ###
