"""init schema

Revision ID: 67afbf298baf
Revises: 89f6bd03bfd2
Create Date: 2025-10-06 07:00:14.016220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67afbf298baf'
down_revision: Union[str, None] = '89f6bd03bfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('Right_TX_UUID', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Earbud_UUIDs', 'Right_TX_UUID')
    # ### end Alembic commands ###
