"""init schema

Revision ID: 89f6bd03bfd2
Revises: faf2e650d46e
Create Date: 2025-10-06 06:59:21.360673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f6bd03bfd2'
down_revision: Union[str, None] = 'faf2e650d46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Earbud_UUIDs', 'Right_TX_UUID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('Right_TX_UUID', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
