"""init schema

Revision ID: c5248d9c2a26
Revises: dcf123844a25
Create Date: 2025-10-08 06:11:23.525354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5248d9c2a26'
down_revision: Union[str, None] = 'dcf123844a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('Earbud_UUIDs_user_Id_key', 'Earbud_UUIDs', type_='unique')
    op.create_unique_constraint(None, 'Earbud_UUIDs', ['user_id'])
    op.drop_constraint('Earbud_UUIDs_user_Id_fkey', 'Earbud_UUIDs', type_='foreignkey')
    op.create_foreign_key(None, 'Earbud_UUIDs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Earbud_UUIDs', 'user_Id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('user_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Earbud_UUIDs', type_='foreignkey')
    op.create_foreign_key('Earbud_UUIDs_user_Id_fkey', 'Earbud_UUIDs', 'users', ['user_Id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Earbud_UUIDs', type_='unique')
    op.create_unique_constraint('Earbud_UUIDs_user_Id_key', 'Earbud_UUIDs', ['user_Id'])
    op.drop_column('Earbud_UUIDs', 'user_id')
    # ### end Alembic commands ###
