"""init schema

Revision ID: dcf123844a25
Revises: 67afbf298baf
Create Date: 2025-10-08 06:09:38.865723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf123844a25'
down_revision: Union[str, None] = '67afbf298baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('user_Id', sa.Integer(), nullable=True))
    op.drop_constraint('Earbud_UUIDs_User_Id_key', 'Earbud_UUIDs', type_='unique')
    op.create_unique_constraint(None, 'Earbud_UUIDs', ['user_Id'])
    op.drop_constraint('Earbud_UUIDs_User_Id_fkey', 'Earbud_UUIDs', type_='foreignkey')
    op.create_foreign_key(None, 'Earbud_UUIDs', 'users', ['user_Id'], ['id'], ondelete='CASCADE')
    op.drop_column('Earbud_UUIDs', 'User_Id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Earbud_UUIDs', sa.Column('User_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Earbud_UUIDs', type_='foreignkey')
    op.create_foreign_key('Earbud_UUIDs_User_Id_fkey', 'Earbud_UUIDs', 'users', ['User_Id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Earbud_UUIDs', type_='unique')
    op.create_unique_constraint('Earbud_UUIDs_User_Id_key', 'Earbud_UUIDs', ['User_Id'])
    op.drop_column('Earbud_UUIDs', 'user_Id')
    # ### end Alembic commands ###
