"""init schema

Revision ID: faf2e650d46e
Revises: eb594d2b6856
Create Date: 2025-10-06 06:53:03.141758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf2e650d46e'
down_revision: Union[str, None] = 'eb594d2b6856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Earbud_UUIDs',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Left_Service_UUID', sa.Text(), nullable=True),
    sa.Column('Left_RX_UUID', sa.Text(), nullable=True),
    sa.Column('Left_TX_UUID', sa.Text(), nullable=True),
    sa.Column('Right_Service_UUID', sa.Text(), nullable=True),
    sa.Column('Right_RX_UUID', sa.Text(), nullable=True),
    sa.Column('Right_TX_UUID', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True, comment='Shared serial number for both earbuds'),
    sa.Column('left_mac_address', sa.String(length=17), nullable=True, comment='MAC address format: XX:XX:XX:XX:XX:XX'),
    sa.Column('left_firmware_upload', sa.Boolean(), nullable=True, comment='Firmware upload status'),
    sa.Column('left_firmware_version_eeg', sa.String(length=20), nullable=True, comment='EEG firmware version'),
    sa.Column('left_firmware_version_audio', sa.String(length=20), nullable=True, comment='Audio firmware version'),
    sa.Column('left_last_upload_date', sa.Date(), nullable=True, comment='Last firmware upload date'),
    sa.Column('left_deployment_status', sa.String(length=100), nullable=True, comment='Current deployment status'),
    sa.Column('left_comments', sa.Text(), nullable=True, comment='Additional comments or notes'),
    sa.Column('right_mac_address', sa.String(length=17), nullable=True, comment='MAC address format: XX:XX:XX:XX:XX:XX'),
    sa.Column('right_firmware_upload', sa.Boolean(), nullable=True, comment='Firmware upload status'),
    sa.Column('right_firmware_version_eeg', sa.String(length=20), nullable=True, comment='EEG firmware version'),
    sa.Column('right_firmware_version_audio', sa.String(length=20), nullable=True, comment='Audio firmware version'),
    sa.Column('right_last_upload_date', sa.Date(), nullable=True, comment='Last firmware upload date'),
    sa.Column('right_deployment_status', sa.String(length=100), nullable=True, comment='Current deployment status'),
    sa.Column('right_comments', sa.Text(), nullable=True, comment='Additional comments or notes'),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['User_Id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('User_Id')
    )
    op.create_index(op.f('ix_Earbud_UUIDs_ID'), 'Earbud_UUIDs', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Earbud_UUIDs_ID'), table_name='Earbud_UUIDs')
    op.drop_table('Earbud_UUIDs')
    # ### end Alembic commands ###
